sudo: required 

language: go

services: 
    - docker

install:
    - go get -u github.com/golang/dep/... 
    - dep ensure
    - cp config/config.go.template config/config.go
    - docker build -t groot-api-gateway .
#    - docker run groot-api-gateway ./build/groot-api-gateway 

script: 
    - ./build.sh

notifications:
    email: false
