sudo: required 

language: go

services: 
    - docker

install:
    - go get github.com/gorilla/mux
    - go get github.com/boltdb/bolt
    - go get github.com/kennygrant/sanitize
    - go get github.com/acm-uiuc/arbor
    - cp config/config.go.template config/config.go
    - docker build -t groot-api-gateway .
    - docker run groot-api-gateway ./build/groot-api-gateway 

script: 
    - ./build.sh

notifications:
    email: false
